import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const lang = process.env.DOCUSAURUS_CURRENT_LOCALE

const sidebars: SidebarsConfig = {
  tutorials: [
    'tutorials/environment',
    'tutorials/skill',
    'tutorials/quickstart',
    'tutorials/codespace',
    'tutorials/vm',
    // {
    //   type: 'category',
    //   label: lang === 'en' ? 'Examples' : '示例',
    //   items: [
    //     'tutorials/Examples/io',
    //     'tutorials/Examples/hotkey',
    //     'tutorials/Examples/tcpip',
    //     'tutorials/Examples/grip'
    //   ]
    // }
  ],
  api: [{ type: 'autogenerated', dirName: 'api' }],
  components: [{ type: 'autogenerated', dirName: 'components' }],
  lua: [{ type: 'autogenerated', dirName: 'lua' }],
  examples: [
    {
      type: 'category',
      label: 'Agent Skill',
      items: [
        'examples/Agent/Modbus-RTU',
        // 'examples/Agent/IO',
        // 'examples/Agent/UI'
      ]
    },
    {
      type: 'category',
      label: lang === 'en' ? 'Basic Examples' : '基础示例',
      items: [
        'examples/Basic/io',
        'examples/Basic/hotkey',
        'examples/Basic/tcpip',
        'examples/Basic/grip'
      ]
    }
  ]
}

export default sidebars
